// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkDkxCncyyK9XlqXYYxaWv7ZZr1KIo3eg',
    appId: '1:801552591483:web:06d4a1e601673f0dc150de',
    messagingSenderId: '801552591483',
    projectId: 'cvproject-dcce1',
    authDomain: 'cvproject-dcce1.firebaseapp.com',
    storageBucket: 'cvproject-dcce1.firebasestorage.app',
    measurementId: 'G-K7ZT27EKC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb4uhj24U-nErqYHvUA6MC1hFjGm44dpI',
    appId: '1:801552591483:android:8303f32f387d9defc150de',
    messagingSenderId: '801552591483',
    projectId: 'cvproject-dcce1',
    storageBucket: 'cvproject-dcce1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPTyjLxMkVuceYhana_s5rWW1ul0TbnEM',
    appId: '1:801552591483:ios:91a8016a4ed44fa4c150de',
    messagingSenderId: '801552591483',
    projectId: 'cvproject-dcce1',
    storageBucket: 'cvproject-dcce1.firebasestorage.app',
    iosBundleId: 'com.example.cvProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPTyjLxMkVuceYhana_s5rWW1ul0TbnEM',
    appId: '1:801552591483:ios:91a8016a4ed44fa4c150de',
    messagingSenderId: '801552591483',
    projectId: 'cvproject-dcce1',
    storageBucket: 'cvproject-dcce1.firebasestorage.app',
    iosBundleId: 'com.example.cvProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkDkxCncyyK9XlqXYYxaWv7ZZr1KIo3eg',
    appId: '1:801552591483:web:8f393dc493d47020c150de',
    messagingSenderId: '801552591483',
    projectId: 'cvproject-dcce1',
    authDomain: 'cvproject-dcce1.firebaseapp.com',
    storageBucket: 'cvproject-dcce1.firebasestorage.app',
    measurementId: 'G-95DNXS88C8',
  );
}
